---

group: stable
dist: bionic

language: python
python: "2.7"

branches:
  only:
    - develop
    - master

env:
  - ANSIBLE_INSTALL_VERSION=2.6.20.0
  - ANSIBLE_INSTALL_VERSION=2.7.14.0
  - ANSIBLE_INSTALL_VERSION=2.8.6.0

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Download dependencies
  - make test_deps

script:
  - make lint
  - make test_ansible

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
